sources:
  # Western Liberal Democratic Perspective
  - name: "BBC World News"
    type: "rss"
    url: "http://feeds.bbci.co.uk/news/world/rss.xml"
    lang: "en"
    diversity_score: 6.5
    perspective: "Western Liberal, Public Broadcasting"
    region: "Europe/UK"

  - name: "The Guardian World News"
    type: "rss"
    url: "https://www.theguardian.com/world/rss"
    lang: "en"
    diversity_score: 5.5
    perspective: "Western Left-Liberal"
    region: "Europe/UK"

  - name: "NPR World News"
    type: "rss"
    url: "https://feeds.npr.org/1004/rss.xml"
    lang: "en"
    diversity_score: 5.8
    perspective: "US Liberal, Public Broadcasting"
    region: "North America/USA"

  - name: "ABC News International"
    type: "rss"
    url: "https://feeds.abcnews.com/abcnews/internationalheadlines"
    lang: "en"
    diversity_score: 5.2
    perspective: "US Mainstream, Commercial"
    region: "North America/USA"

  # Middle Eastern Perspectives
  - name: "Al Jazeera English"
    type: "rss"
    url: "https://www.aljazeera.com/xml/rss/all.xml"
    lang: "en"
    diversity_score: 8.5
    perspective: "Middle Eastern, Pan-Arab"
    region: "Middle East/Qatar"

  - name: "Press TV International"
    type: "rss"
    url: "https://www.presstv.ir/rss.xml"
    lang: "en"
    diversity_score: 9.2
    perspective: "Iranian State Broadcasting"
    region: "Middle East/Iran"

  - name: "Jerusalem Post World News"
    type: "rss"
    url: "https://www.jpost.com/rss/rssfeedsheadlines.aspx"
    lang: "en"
    diversity_score: 7.1
    perspective: "Israeli Right-Center"
    region: "Middle East/Israel"

  # Russian/Eastern European Perspective
  - name: "RT International"
    type: "rss"
    url: "https://www.rt.com/rss/"
    lang: "en"
    diversity_score: 9.5
    perspective: "Russian State, Pro-Kremlin"
    region: "Eastern Europe/Russia"

  - name: "TASS World"
    type: "rss"
    url: "https://tass.com/rss/v2.xml"
    lang: "en"
    diversity_score: 9.0
    perspective: "Russian Official News Agency"
    region: "Eastern Europe/Russia"

  # Chinese Perspective
  - name: "China Daily World"
    type: "rss"
    url: "http://www.chinadaily.com.cn/rss/world_rss.xml"
    lang: "en"
    diversity_score: 8.8
    perspective: "Chinese State English-Language"
    region: "East Asia/China"

  - name: "Global Times"
    type: "rss"
    url: "https://www.globaltimes.cn/rss/outbrain.xml"
    lang: "en"
    diversity_score: 8.9
    perspective: "Chinese Nationalist, CCP-Aligned"
    region: "East Asia/China"

  - name: "Xinhua World News"
    type: "rss"
    url: "http://www.xinhuanet.com/english/rss/worldrss.xml"
    lang: "en"
    diversity_score: 8.7
    perspective: "Chinese State News Agency"
    region: "East Asia/China"

  # Asian Perspectives
  - name: "The Hindu International"
    type: "rss"
    url: "https://www.thehindu.com/news/international/?service=rss"
    lang: "en"
    diversity_score: 7.2
    perspective: "Indian Liberal, Non-Aligned"
    region: "South Asia/India"

  - name: "Times of India World"
    type: "rss"
    url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms"
    lang: "en"
    diversity_score: 6.9
    perspective: "Indian Centrist, Economic Focus"
    region: "South Asia/India"

  - name: "Channel NewsAsia World"
    type: "rss"
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511"
    lang: "en"
    diversity_score: 6.6
    perspective: "Singaporean State Broadcasting"
    region: "Southeast Asia/Singapore"

  # African Perspectives
  - name: "AllAfrica Global"
    type: "rss"
    url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf"
    lang: "en"
    diversity_score: 8.2
    perspective: "Pan-African News Aggregator"
    region: "Africa/Continental"

  - name: "Mail & Guardian Africa"
    type: "rss"
    url: "https://mg.co.za/rss/"
    lang: "en"
    diversity_score: 7.9
    perspective: "South African Progressive"
    region: "Africa/South Africa"

  - name: "Egypt Independent"
    type: "rss"
    url: "https://www.egyptindependent.com/feed/"
    lang: "en"
    diversity_score: 7.7
    perspective: "Egyptian Independent"
    region: "Africa/Egypt"

  # Latin American Perspectives
  - name: "Brazil Reports"
    type: "rss"
    url: "https://brazilreports.com/feed/"
    lang: "en"
    diversity_score: 7.4
    perspective: "Brazilian Independent English"
    region: "South America/Brazil"

  - name: "Mexico News Daily"
    type: "rss"
    url: "https://mexiconewsdaily.com/feed/"
    lang: "en"
    diversity_score: 7.3
    perspective: "Mexican English-Language"
    region: "North America/Mexico"

  - name: "Colombia Reports"
    type: "rss"
    url: "https://colombiareports.com/feed/"
    lang: "en"
    diversity_score: 7.8
    perspective: "Colombian Independent English"
    region: "South America/Colombia"

  # International Organizations
  - name: "UN News"
    type: "rss"
    url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml"
    lang: "en"
    diversity_score: 5.0
    perspective: "Multilateral, Diplomatic"
    region: "Global/International"

  - name: "VOA News World"
    type: "rss"
    url: "https://www.voanews.com/api/epiqq"
    lang: "en"
    diversity_score: 5.9
    perspective: "US Government Broadcasting"
    region: "North America/USA"

  # Alternative/Independent
  - name: "The Intercept"
    type: "rss"
    url: "https://theintercept.com/feed/?rss"
    lang: "en"
    diversity_score: 6.8
    perspective: "US Independent Left, Investigative"
    region: "North America/USA"

  - name: "Global Voices"
    type: "rss"
    url: "https://globalvoices.org/feed/"
    lang: "en"
    diversity_score: 7.8
    perspective: "Citizen Media, Global South Focus"
    region: "Global/International"

  # European Alternative Perspectives
  - name: "Euronews World"
    type: "rss"
    url: "https://www.euronews.com/rss?level=theme&name=news"
    lang: "en"
    diversity_score: 6.3
    perspective: "European Multilingual"
    region: "Europe/France"

  # Canadian Perspective
  - name: "CBC World"
    type: "rss"
    url: "https://www.cbc.ca/cmlink/rss-world"
    lang: "en"
    diversity_score: 6.1
    perspective: "Canadian Public Broadcasting"
    region: "North America/Canada"

  # Australian/Oceanic Perspective
  - name: "Sydney Morning Herald World"
    type: "rss"
    url: "https://www.smh.com.au/rss/world.xml"
    lang: "en"
    diversity_score: 6.0
    perspective: "Australian Liberal"
    region: "Oceania/Australia"

  - name: "Australian Broadcasting Corporation"
    type: "rss"
    url: "https://www.abc.net.au/news/feed/51120/rss.xml"
    lang: "en"
    diversity_score: 6.4
    perspective: "Australian Public Broadcasting"
    region: "Oceania/Australia"